### ISSUE TITLE
Shotgun weapons showing multiple damage popoffs per shot

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#34] opened 2019-04-28 17:28 UTC
The way damage popoffs for simultaneous pellets used to work is that it added up the damage from all of the pellets and drew only one damage popoff showing the sum total of the damage dealt, but in the current version, it's showing one damage popoff per pellet, from players and monsters alike, so it's much harder to tell the real damage being dealt from shotgun-based weapons.

**Comment by Demiosis** [comment] 2019-04-28 17:43
You're sure you weren'T hitting multiples enemies? Which each their own damage numbers? I don't recall this happening and been playing with shotty with all my chars since they are such good close combat back up weps!

Or maybe a specific unique weapon? with a specific mod? Would need more data tbh.. XD

**Comment by KuromeKT** [comment] 2019-05-06 22:35
Yes, I'm sure. It happens with all shotgun-type weapons that fire multiple bullets/pellets at the same time, so it should be trivial to replicate this bug.

**Comment by Demiosis** [comment] 2019-05-08 18:47
Seem like you're using a wrong version of Gzdoom or using the launcher (never had much sucess running the mod properly with it if I really wanna be honest with you... ^^')' or something similar , make sure you have latest Gzdoom files , latest doomrpg files + other mods like Drla and finally run your file list in a .bat file.

Example of a .Bat file:

"GZDOOM.exe" -file "mappackname.wad" "DoomRL_Arsenal_1.1.1.pk3" "DoomRL_Monsters_Beta_7.1.pk3" "doomrl_arsenal_hud_1.05.wad" "DoomRPG.zip" "DoomRPG-RLArsenal.zip" "DoomRPG-RLMonsters.zip" "Doomrpg-BrightMaps.zip"

Also, its compatible with this mod list :

DoomRL Arsenal - [1.1.1] [MP-B7.1].
LegenDoom v2.5.
Colourful Hell v0.97b.
Custom version of Jimmy's Jukebox Instant Randomizer has been included which allows DRPG's map events and Outpost music to play.

BUT, do not put more than one at a time or else it WILL explode and burn ^^'

**Comment by KuromeKT** [comment] 2019-05-09 22:06
No. I've been using GZDoom 3.7.2 this whole time, and the pellets were working as intended a couple of months ago.

**Comment by Demiosis** [comment] 2019-05-10 17:04
but on all this wall of text I pointed 2 other important things.And you seem to just have skipped them. I'll ask again : Do you use the launcher? if yes refrain from doing so and use / create a .bat instead. all your problem MOST likely all come from the launcher. Also , you didnt not list your mod list. How do you expect me to help if you don't give information? XD

**Comment by KuromeKT** [comment] 2019-05-11 00:37
I've never used the DRPG launcher, as I've always ran the mod via ZDoom Launcher instead. The order of wads is the same as yours, except no HUD wad and Brightmaps comes before the DRPG DRLA wads (and Brightmaps in itself is an inconsequential wad and its placing in the order shouldn't matter).

You're completely missing the point here. This bug did not happen before and was introduced in a recent update. I changed literally nothing in my settings. All I did was replace the respective wads with their newer counterparts -- no changes in the in-game settings and no changes in ZDoom Launcher. It's obvious this is not a freak accident caused by my personally mishandling the wads, so I'd appreciate it if you'd stopped being so sceptical.

**Comment by Sumwunn** [comment] 2019-05-14 02:59
This was caused by my transition of DamageNumbers script to ZScript. WorldThingDamaged seems to get called for every single pellet that hits the enemy, hence the duplicate numbers.

I'll took a closer look at this when the HP bug is confirmed fixed.

**Comment by Sumwunn** [comment] 2019-06-14 20:05
Hey guys, I've spent some time with this issue and it's been quite the pickle.

Issues:
1. Accumulating damage each time the script is called kinda works (little hacky with ACS) but required adding a number to track the damage to the monster's data struct which incurred a 60+ KB increase on DRPGs lib. This solution feels overkill. I think ACS is not the route to go for this.
2.  I don't want to revert the DamageNumbers() code because it incurred quite the performance hit.

Since I've moved all player popoffs to their own function it left DamageNumbers() in a pretty basic shape (only 12 lines). I'm thinking about removing that and pointing people to Xaser's DamNums instead. It's written in ZScript, much more developed, customisable and doesn't have these issues.

For now you can disable DRPG's DamNum's in the options and load that.

**Comment by Demiosis** [comment] 2019-06-16 18:34
Tbh damage popoffs are only used in the outpost for dps testing anyway so its not a big loss.Also btw, speaking bout dps charting, you sould officialise Elkinda's outpost map and make it the new official one with the new shooting range having 3 dps target is so much better than ONLY one OVER the arena's counter.... XD (reloaded the game once too many because of hitting the people under it....)

**Comment by Demiosis** [comment] 2019-06-26 18:48
All Credits goes to Elkinda the chaplain of cheese for the modifications on this  outpost map


[Outpost.zip](https://github.com/Sumwunn/DoomRPG/files/3331525/Outpost.zip)

**Comment by Sumwunn** [comment] 2019-06-30 02:41
Huh alright. I'll make a sign for it and commit soon.

Thanks!

**Comment by Sumwunn** [comment] 2019-06-30 23:28
Included the tweaked Outpost map in https://github.com/Sumwunn/DoomRPG/commit/bf61ace7c940fe1fb7fd628ec3dd6a42b5069f38.

**Comment by Sumwunn** [comment] 2020-03-14 00:09
Forgot about this issue. 

This was resolved in https://github.com/Sumwunn/DoomRPG/commit/f62e866bb6d3fdd0b01e12655a0058aa3640cfe7 for those wondering.

**Closed by Sumwunn** 2020-03-14 00:09 UTC
