### ISSUE TITLE
Abnormal loot in common crate

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#15] opened 2019-02-06 04:53 UTC
Common loot balance is currently out of wack :

No events, map 1, nightmare diff : 2 common crates with many a shield parts(total 5) + a Heavy assault shotgun (Exotic + 2 regular mods basic assembly) once again I do feel like its too much, specially compared to old Drpg versions ^^

![commoncrate1](https://user-images.githubusercontent.com/5500931/52321110-001ec200-29a1-11e9-9425-cab1be282a7d.png)
![commoncrate2](https://user-images.githubusercontent.com/5500931/52321111-00b75880-29a1-11e9-94d8-e4f9d7de7227.png)

(forgot to take screenshot of the 1st one but I've assembled the 3 parts I got from it on the 1st screenshot instead)
plus i wanted to show it was rly on the 1st map with a lowbie

If you want more screenshots as proof it will be my pleasure to deliver my good sir

**Comment by Demiosis** [comment] 2019-02-06 05:20
New sets of pictures , as you can see only 2 common crate produced from repeated runs from that 1st level have loot that feel like an actual common crate.

![screenshot_doom_20190206_000159](https://user-images.githubusercontent.com/5500931/52321872-
ccde3200-29a4-11e9-8d25-96111b1da3ca.png)
![screenshot_doom_20190206_000412](https://user-images.githubusercontent.com/5500931/52321873-ccde3200-29a4-11e9-85c1-562af8f51d3f.png)
![screenshot_doom_20190206_000656](https://user-images.githubusercontent.com/5500931/52321874-cd76c880-29a4-11e9-82cb-f6d0e276740a.png)
![screenshot_doom_20190206_000805](https://user-images.githubusercontent.com/5500931/52321875-cd76c880-29a4-11e9-9543-325a3a5b7e44.png)
![screenshot_doom_20190206_001238](https://user-images.githubusercontent.com/5500931/52321876-cd76c880-29a4-11e9-893f-b11d556a4c72.png)
![screenshot_doom_20190206_001506](https://user-images.githubusercontent.com/5500931/52321877-cd76c880-29a4-11e9-9e93-9b118da6aab9.png)
![screenshot_doom_20190206_001600](https://user-images.githubusercontent.com/5500931/52321878-cd76c880-29a4-11e9-9772-b4fb74850576.png)
![screenshot_doom_20190206_001705](https://user-images.githubusercontent.com/5500931/52321879-ce0f5f00-29a4-11e9-9954-4f7954629d8e.png)

**Comment by worldendDominator** [comment] 2019-02-06 06:10
Finding a heavy ASG in a crate is impossible (assemblies have rarity -1, and crate items are picked only from positive rarities), so you must have mistaken that for something else.
Other than that, looking at the code, nothing seems broken. Item amounts seem reasonable, and a Common crate may have shield parts worth up to 20k (and 5% chance for up to 35k).

If you have suggestions to change drop rates, feel free to share.

**Comment by Demiosis** [comment] 2019-02-06 08:12
The Hvy assault shotty was on the ground but still on a map 1. When I played with [0.10.0 Beta] I can guarantee you that I never ever found a shield part in a common crate , they started appearing much later in uncommon + crates and in much farther maps like 15+  before i even start finding something i n the shield part departmenet, made for a more balanced and challenging game, right now if you find a full basic shield it double your hp at level 1 + the armor you could have on if you put the option... the formers/sgt/chaigunner/imps/demon/lost souls will hit you for peanuts compared to the combined shield/hp you will have thus never be in real danger for at least 10+ map if you know a bit what you're doing.

**Comment by Sumwunn** [comment] 2019-02-07 01:25
> No events, map 1, nightmare diff : 2 common crates with many a shield parts(total 5)

DRPG won't spawn any crates (or anything at all) with a new character unless you have changed your starting options to a higher level/rank/stats/luck etc. Perhaps you should refresh your gzdoom config.

_OR_

The map (which wad is that btw?) you're playing on has a load of spheres which are getting replaced with crates. This is more of a map balance issue rather than with DRPG, it wouldn't be fair to reduce the spawn chance because then you may not see any on say, the IWAD maps.

I do agree that getting a load of shield accessories in a chest is a bit much but there's so many of them in this mod that it's hard to balance it all properly.
I could simply limit one shield part per crate and perhaps up the rarities of the lower end ones.

Also the loot chances/rates are completely untouched from 0.10.0 so it seems your experiences between my build that were purely RNG. I cannot think of any other reason.

> they started appearing much later in uncommon + crates and in much farther maps like 15+

I think it might be best to expand the loot generator itself rather than mucking with static balance variables, hmm.

**Comment by Demiosis** [comment] 2019-02-07 02:02
The series of screenshots was taken on multiples runs(like 10 or so) on the same map 1 from a large oblige map. Max number of crate I've seen on the map was 3 iirc which is expected since there was a lot of secrets generated on that map, beside its not that im not expecting crates its that im not expecting common crates on 1st level.. only basics ^^' can't this be tied to character level? would make much more sense tbh.  I'll reset my configs but im fairly sure that if I actually modified something it was on the nerfing end of the spectrum(except the armor stacking with shield thing cauz, its an rpg , stacking things is all whats its about XP) Also, I meant I was using Kyle873's version but not 0.10.0 the one before that which had much more balanced loot.

**Comment by Demiosis** [comment] 2019-02-07 02:47
Full settings reset , multiples runs on a level 1 map on nightmare(oblige generated map) Tally : Basic crates :7 (2 of which had shield parts)
common crates: 9, uncommon:2, superior:1 and found Hell's Reign also on map 1..
Maybe tie crates / guns / armor generation to player level? I really do not see how to better fix this tbh..

![screenshot_doom_20190206_211547](https://user-images.githubusercontent.com/5500931/52387417-281d2c80-2a58-11e9-9771-59f6cefda9c4.png)
![screenshot_doom_20190206_212145](https://user-images.githubusercontent.com/5500931/52387418-281d2c80-2a58-11e9-8b7d-01a2f12bcfe8.png)
![screenshot_doom_20190206_212313](https://user-images.githubusercontent.com/5500931/52387419-281d2c80-2a58-11e9-9ab4-6365a670ec1d.png)
![screenshot_doom_20190206_212426](https://user-images.githubusercontent.com/5500931/52387420-281d2c80-2a58-11e9-9318-c23a611bb5b3.png)
![screenshot_doom_20190206_212456](https://user-images.githubusercontent.com/5500931/52387421-281d2c80-2a58-11e9-938b-814d85b9e66f.png)
![screenshot_doom_20190206_212526](https://user-images.githubusercontent.com/5500931/52387422-28b5c300-2a58-11e9-81bd-110ae45a0c9b.png)
![screenshot_doom_20190206_212615](https://user-images.githubusercontent.com/5500931/52387423-28b5c300-2a58-11e9-91f7-7d70f20fa29f.png)
![screenshot_doom_20190206_212717](https://user-images.githubusercontent.com/5500931/52387424-28b5c300-2a58-11e9-9bc0-6e0e5f16f2e6.png)
![screenshot_doom_20190206_212754](https://user-images.githubusercontent.com/5500931/52387425-28b5c300-2a58-11e9-8b9d-b2f5b972bd00.png)
![screenshot_doom_20190206_212825](https://user-images.githubusercontent.com/5500931/52387426-294e5980-2a58-11e9-9f0a-150be8105bdc.png)
![screenshot_doom_20190206_212859](https://user-images.githubusercontent.com/5500931/52387427-294e5980-2a58-11e9-9fd4-f90ca2eba4ab.png)
![screenshot_doom_20190206_212950](https://user-images.githubusercontent.com/5500931/52387428-294e5980-2a58-11e9-949d-9393d7ff8a04.png)
![screenshot_doom_20190206_213016](https://user-images.githubusercontent.com/5500931/52387429-294e5980-2a58-11e9-9870-ca0c47e6f0a8.png)
![screenshot_doom_20190206_213042](https://user-images.githubusercontent.com/5500931/52387430-29e6f000-2a58-11e9-8bbe-5a588a80dd3f.png)
![screenshot_doom_20190206_213144](https://user-images.githubusercontent.com/5500931/52387431-29e6f000-2a58-11e9-9a82-bdb782b02179.png)
![screenshot_doom_20190206_213351](https://user-images.githubusercontent.com/5500931/52387432-29e6f000-2a58-11e9-93a6-830a79e2a4e6.png)
![screenshot_doom_20190206_213801](https://user-images.githubusercontent.com/5500931/52387433-2a7f8680-2a58-11e9-8573-b9313ed5fb52.png)
![screenshot_doom_20190206_213817](https://user-images.githubusercontent.com/5500931/52387434-2a7f8680-2a58-11e9-8734-f7993951cea6.png)
![screenshot_doom_20190206_213910](https://user-images.githubusercontent.com/5500931/52387435-2a7f8680-2a58-11e9-9911-23d1d0ce300c.png)
![screenshot_doom_20190206_214010](https://user-images.githubusercontent.com/5500931/52387436-2a7f8680-2a58-11e9-9070-ec42a35f1a6d.png)
![screenshot_doom_20190206_214057](https://user-images.githubusercontent.com/5500931/52387437-2b181d00-2a58-11e9-896e-f3cfd7d6fdff.png)
![screenshot_doom_20190206_214212](https://user-images.githubusercontent.com/5500931/52387438-2b181d00-2a58-11e9-96e8-dd603ccaab14.png)

**Comment by worldendDominator** [comment] 2019-02-07 06:30
How many runs did that involve?
All shield parts have Rarity of at least 1. Items in Basic crates have rarity 0, and each has 1/20 chance to increase by 1. I think it seems fair.
Finding Hell's Reign on the map is an Arsenal thing. Any weapon spawn has a very low chance of spawning an exotic, assembled or unique weapon.

**Comment by Demiosis** [comment] 2019-02-07 06:42
About 10-12 runs not above 15 for sure. Also ok for Arsenal, I have a hard time knowing what belong to what mod sry , I guess it does not help that I never played one without the other ^^'''. Guess Yholl and Sumwumm should talk about this issue , when it crop up it make everything so easy.. XD , an extreme example of this is Death's gaze at level 1 as scout , you'll never EVER want another other gun except maybe Casull/Jackal combo to clean the ez crud but switch back on Death's gaze to take care of the serious stuff like baron + and bosses.

**Comment by Sumwunn** [comment] 2019-02-08 23:39
I'd been racking my head with the loot code for a few days and honestly the only changes I would really make would be restricting how many shield parts are found in crates, also maybe removing basic package from loot all together and making it somewhat more expensive so you have to buy it instead.

I'm not sure whether I'll limit parts via a hard limit or via chance. I think customisable chance is fairer.

Unless if worldendDominator wants to change anything I'm just gonna limit my changes to the shields for now.

**Comment by Demiosis** [comment] 2019-02-09 02:40
Ok, but seriously , can't you tie item spawning in the map/ in crates tied to player level? it would solve everything but it may be hard to implement. Though it should be doable since you already have a gauge in monster level/stat system : monster level weight slider (Im assuming this check your level and add an additional fraction of that to the spawned monsters on top of the monster map weight)

**Comment by Sumwunn** [comment] 2019-02-09 03:10
Crate item rarity is already influenced by average player level + luck as seen [here](https://github.com/Sumwunn/DoomRPG/blob/master/DoomRPG/scripts/Crate.c#L51). This is how it's been since 0.9, I think that's the version you came from? Can you try and confirm this please?

Shield parts appearing in basic crates is caused by a [rarity chance modifier](https://github.com/Sumwunn/DoomRPG/blob/master/DoomRPG/scripts/ItemData.c#L1066) (I don't know what else to call that code lol.

This code is newer than 0.9 which can cause shield parts to appear in basic crates. I can add a switch for this.

You have to bear in mind that 0.10+ utilizes a rarity system which all items have a rarity assigned, so loot is going to be inherently different.

Apart from re-balancing every rarity in the mod (oh god), I don't see much else I can do.

**Comment by Demiosis** [comment] 2019-02-09 04:10
Yhea this is most likely what broke the Rng in that case... ^^' You should indeed put a switch or nerf it heavily... XD and sorry I don't have the exact version I used in ye oldee timee but most likely BEFORE this rarity chance modifier was a thing!!

**Comment by Sumwunn** [comment] 2019-02-09 04:33
Eh, don't worry about it. Pretty sure 0.9 is the one.

I'll commit the switch addition in experimental in the morning and then close this issue so I can move onto the others.

**Comment by Demiosis** [comment] 2019-02-09 04:42
https://i.imgur.com/XJyemeI.jpg

**Comment by Sumwunn** [comment] 2019-02-09 17:13
Lol.
Done.

Relevant commits:
https://github.com/Sumwunn/DoomRPG/commit/624b22d405f3c8af9fc3044e4c3e3a98026e1ec8
https://github.com/Sumwunn/DoomRPG/commit/ae801c1ac2f4eb548c4b2383f250266be7f970d0

**Closed by Sumwunn** 2019-02-09 17:13 UTC
