### ISSUE TITLE
Nightmare Soul, Hellmine and De-Vile don't give XP on death

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#38] opened 2019-05-04 01:46 UTC
Pretty much what the title says. The De-Vile still drops credits and has assigned stats to it, but it gives you no XP when killed.

**Comment by Demiosis** [comment] 2019-05-11 17:10
Confirmed for nightmare souls. Tried a oblige generated level with only lost souls enemies and used nightmare difficulty and was not able to receive a smidge of Xp.

**Comment by Sumwunn** [comment] 2019-06-18 23:24
Yeah the Nightmare Soul & Hellmine both have the MF_NOXP | MF_NOAURA | MF_NODROPS flags.
The original idea behind this is because Lost Souls get spewed by elementals which can result in XP spam. However I do not recall seeing any monsters spew those two guys? I'll probably take away the flag in that case but I'll leave the others because I don't think Souls are worthy of those flags though haha.

The De-Vile though has no flags though; so that's strange.

**Comment by Demiosis** [comment] 2019-06-19 23:12
Iirc nightmare elemental spawn those when not directly engaged with a player hurm or was it a nightmare elemental mission bosses... well one of those summon nightmare souls.

**Comment by KuromeKT** [comment] 2019-06-20 17:33
Regular Lost Souls give you XP as normal when spawned in the map, but not when spawned by Pain Elementals. Perhaps you could ensure the same is true for the other Lost Soul-type monsters?

**Comment by Sumwunn** [comment] 2019-07-03 04:12
I've made some progress on this.

With ZScript I can detect if a Lost Soul is map based. So anything else I can apply the appropriate flags. However I can only do this reliably with WorldThingDied. So that means I can't set the noaura on the fly; it can only be statically defined.
I think it would be best if Lost Soul's had no auras whatsoever? I'm undecided at the moment.

**Comment by Demiosis** [comment] 2019-07-04 17:24
map lost souls could have auras , anyway aura lost souls aren't a problem usually its when you go into hellknight territory and higher that aura monsters start to be dangerous. Anything that come from a pain elemental should not have any aurasr else the pain elemental boss will be able to overwhelm you much more easily.

**Comment by KuromeKT** [comment] 2019-08-20 06:23
Lost Souls not having auras at all sounds fine with me, if it's too cumbersome to implement map-based Lost Souls with auras/XP/drops. As long as the behaviour is consistent to all Lost Soul-type monsters.

**Comment by Sumwunn** [comment] 2019-10-26 21:11
Hey guys I believe I've almost cracked this issue.

Now, Lost Soul's other than map-based ones will not give you XP and this covers mission-based ones as well. 

Does anybody think that's unfair? I mean you still paid for completing the mission.
I'm just asking because it saves me a chunk of work not to detect mission-based monsters.

**Comment by FoxMcloud5655** [comment] 2019-10-26 21:23
I'm totally fine with that.  The fact it was even done at all is impressive to me!

**Comment by Sumwunn** [comment] 2019-10-26 22:00
Alrighty then!

I've uploaded the changes into the experimental branch for now.
Post back here if any oddities are discovered as I still need to test it more.

**Comment by Sumwunn** [comment] 2019-11-13 01:57
I've tested this plenty since and have now merged the changes into master.

Enjoy.

**Closed by Sumwunn** 2019-11-13 01:57 UTC
